### ISSUE TITLE
tdwg/ontology/Readme may be misleading

### ISSUE THREAD

**Issue by ramorrismorris** [tdwg/ontology#8]
The gist of tdwg/ontology issue list as of this writing, and (I assume) all the documents and deprecations that will result therefrom, make clear that parts of the TDWG Ontologies are deprecated.  But it's hard to see what is the status of those not mentioned.  (The most likely in use in the wild is TaxonConcept.) The front of tdwg/ontology should have a page named e.g. README_FIRST that briefly summarizes the state of the collection with particular mention of the status of undeprecated ontologies (e.g. whether there is a TG dealing with them or a proposal for such a TG emerging, etc.).  Such a page should clearly suggest that users of undeprecated, but not yet ratified, ontologies should watch the page for current news.

**Comment by baskaufs** [comment]
The current README is really a stub.  I'm intending that it should contain a better explanation of the status and history - at a minimum a reference to Sections 2.4 and 2.6.1 of the [VoMaG report](https://github.com/tdwg/vocab/blob/master/gbif_TDWG_Vocabulary_Management_Task_Group_en_v1.0.pdf) that summarizes such things.  Probably better to actually have such text on the readme or a page linked to the readme called history, status or whatever.  I haven't had time to work on that yet, though.

**Comment by ramorrismorris** [comment]
I considered that.  But in this case it seems critical to make it hard to notice that there are ontologies that are not deprecated, not submitted for acceptance, and  yet possibly in use anyway. I could live with  a warning in README if attention is called to that right within a few lines of the top.  I think it would be really risky to assume that every reader will take the time to read a long README much less look at another document  (unless it has a title something like README_FIRST ... :-)  ).  I'll watch the README edit carefully when you get to it.  I hate it when I chase documentation along a long trail only to feel "Why didn't they tell me that at the beginning?"  Of course, that reflects an opinion that what's most important to me is most important to the majority of readers.  Hence, the real issue here is whether the point I raise is important enough to merit prominence.  We can have that discussion when you get to editing the README.

**Comment by baskaufs** [comment]
@ramorrismorris  Bob, I have finished making the modifications to the ontology files and updated the README.md accordingly.  On the README, I tried to have a clearly demarcated section called "Components of the TDWG Ontology still in use" that includes a listing of the ontologies, a note to "watch this page" as you suggested, and a brief summary of the status of the NCD and TCS standards upon which those ontologies were based.  Please take a look at this to see if resolves your issue.  I will wait to close this issue until I get feedback from you.

@mdoering Markus, I think this is the last issue blocking the wrap up of the TDWG Ontology migration.  There is a [stub page](https://github.com/tdwg/ontology/blob/master/replacements.md) for recommended replacement vocabularies, but I don't think its incompleteness should hold back finishing the migration.  It is unlikely to be complete at any time in the near future.

**Comment by ramorrismorris** [comment]
I like the README now, with one minor suggestion: To the first paragraph add a few sentences something like "Although the TDWG Ontologies were never made a TDWG Standard, some are in use in the wild. It is not recommended that new projects use them without tracking their current status here and on the issue list https://github.com/tdwg/ontology/issues."

This puts in the reader's face explicitly what the risks and remedies are of using them. Savvy readers would probably come to this conclusion reading a few more paragraphs, but I don't think it hurts to have it here too.

**Comment by baskaufs** [comment]
OK, great!  I've made the relevant edits and am going to close this issue.  @mdoering the ball is in your court.
